<?php
/**
 * api/updatereviewofsystems.php Update review of systems.
 *
 * API is allowed to update patient review of systems details.
 * 
 * @package OpenEMR
 * @link    http://www.open-emr.org
 * API SCSMed version 1.5
 * Modified by sgiman, 2016-2019
 */
header("Content-Type:text/xml");
header("Access-Control-Allow-Origin: *");

$ignoreAuth = true;
require_once 'classes.php';
$xml_string = "";
$xml_string = "<reviewofsystems>";

$token = $_GET['token'];
$rosId = $_GET['id'];

$patientId = $_GET['pid'];
$weight_change = $_GET['weight_change'];
$weakness = $_GET['weakness'];
$fatigue = $_GET['fatigue'];
$anorexia = $_GET['anorexia'];
$fever = $_GET['fever'];
$chills = $_GET['chills'];
$night_sweats = $_GET['night_sweats'];
$insomnia = $_GET['insomnia'];
$irritability = $_GET['irritability'];
$heat_or_cold = $_GET['heat_or_cold'];
$intolerance = $_GET['intolerance'];
$change_in_vision = $_GET['change_in_vision'];
$glaucoma_history = $_GET['glaucoma_history'];
$eye_pain = $_GET['eye_pain'];
$irritation = $_GET['irritation'];
$redness = $_GET['redness'];
$excessive_tearing = $_GET['excessive_tearing'];
$double_vision = $_GET['double_vision'];
$blind_spots = $_GET['blind_spots'];
$photophobia = $_GET['photophobia'];
$hearing_loss = $_GET['hearing_loss'];
$discharge = $_GET['discharge'];
$pain = $_GET['pain'];
$vertigo = $_GET['vertigo'];
$tinnitus = $_GET['tinnitus'];
$frequent_colds = $_GET['frequent_colds'];
$sore_throat = $_GET['sore_throat'];
$sinus_problems = $_GET['sinus_problems'];
$post_nasal_drip = $_GET['post_nasal_drip'];
$nosebleed = $_GET['nosebleed'];
$snoring = $_GET['snoring'];
$apnea = $_GET['apnea'];
$breast_mass = $_GET['breast_mass'];
$breast_discharge = $_GET['breast_discharge'];
$biopsy = $_GET['biopsy'];
$abnormal_mammogram = $_GET['abnormal_mammogram'];
$cough = $_GET['cough'];
$sputum = $_GET['sputum'];
$shortness_of_breath = $_GET['shortness_of_breath'];
$wheezing = $_GET['wheezing'];
$hemoptsyis = $_GET['hemoptsyis'];
$asthma = $_GET['asthma'];
$copd = $_GET['copd'];
$chest_pain = $_GET['chest_pain'];
$palpitation = $_GET['palpitation'];
$syncope = $_GET['syncope'];
$pnd = $_GET['pnd'];
$doe = $_GET['doe'];
$orthopnea = $_GET['orthopnea'];
$peripheal = $_GET['peripheal'];
$edema = $_GET['edema'];
$legpain_cramping = $_GET['legpain_cramping'];
$history_murmur = $_GET['history_murmur'];
$arrythmia = $_GET['arrythmia'];
$heart_problem = $_GET['heart_problem'];
$dysphagia = $_GET['dysphagia'];
$heartburn = $_GET['heartburn'];
$bloating = $_GET['bloating'];
$belching = $_GET['belching'];
$flatulence = $_GET['flatulence'];
$nausea = $_GET['nausea'];
$vomiting = $_GET['vomiting'];
$hematemesis = $_GET['hematemesis'];
$gastro_pain = $_GET['gastro_pain'];
$food_intolerance = $_GET['food_intolerance'];
$hepatitis = $_GET['hepatitis'];
$jaundice = $_GET['jaundice'];
$hematochezia = $_GET['hematochezia'];
$changed_bowel = $_GET['changed_bowel'];
$diarrhea = $_GET['diarrhea'];
$constipation = $_GET['constipation'];
$polyuria = $_GET['polyuria'];
$polydypsia = $_GET['polydypsia'];
$dysuria = $_GET['dysuria'];
$hematuria = $_GET['hematuria'];
$frequency = $_GET['frequency'];
$urgency = $_GET['urgency'];
$incontinence = $_GET['incontinence'];
$renal_stones = $_GET['renal_stones'];
$utis = $_GET['utis'];
$hesitancy = $_GET['hesitancy'];
$dribbling = $_GET['dribbling'];
$stream = $_GET['stream'];
$nocturia = $_GET['nocturia'];
$erections = $_GET['erections'];
$ejaculations = $_GET['ejaculations'];
$g = $_GET['g'];
$p = $_GET['p'];
$ap = $_GET['ap'];
$lc = $_GET['lc'];
$mearche = $_GET['mearche'];
$menopause = $_GET['menopause'];
$lmp = $_GET['lmp'];
$f_frequency = $_GET['f_frequency'];
$f_flow = $_GET['f_flow'];
$f_symptoms = $_GET['f_symptoms'];
$abnormal_hair_growth = $_GET['abnormal_hair_growth'];
$f_hirsutism = $_GET['f_hirsutism'];
$joint_pain = $_GET['joint_pain'];
$swelling = $_GET['swelling'];
$m_redness = $_GET['m_redness'];
$m_warm = $_GET['m_warm'];
$m_stiffness = $_GET['m_stiffness'];
$muscle = $_GET['muscle'];
$m_aches = $_GET['m_aches'];
$fms = $_GET['fms'];
$arthritis = $_GET['arthritis'];
$loc = $_GET['loc'];
$seizures = $_GET['seizures'];
$stroke = $_GET['stroke'];
$tia = $_GET['tia'];
$n_numbness = $_GET['n_numbness'];
$n_weakness = $_GET['n_weakness'];
$paralysis = $_GET['paralysis'];
$intellectual_decline = $_GET['intellectual_decline'];
$memory_problems = $_GET['memory_problems'];
$dementia = $_GET['dementia'];
$n_headache = $_GET['n_headache'];
$s_cancer = $_GET['s_cancer'];
$psoriasis = $_GET['psoriasis'];
$s_acne = $_GET['s_acne'];
$s_other = $_GET['s_other'];
$s_disease = $_GET['s_disease'];
$p_diagnosis = $_GET['p_diagnosis'];
$p_medication = $_GET['p_medication'];
$depression = $_GET['depression'];
$anxiety = $_GET['anxiety'];
$social_difficulties = $_GET['social_difficulties'];
$thyroid_problems = $_GET['thyroid_problems'];
$diabetes = $_GET['diabetes'];
$abnormal_blood = $_GET['abnormal_blood'];
$anemia = $_GET['anemia'];
$fh_blood_problems = $_GET['fh_blood_problems'];
$bleeding_problems = $_GET['bleeding_problems'];
$allergies = $_GET['allergies'];
$frequent_illness = $_GET['frequent_illness'];
$hiv = $_GET['hiv'];
$hai_status = $_GET['hai_status'];

if ($userId = validateToken($token)) {
    $user = getUsername($userId);
    $acl_allow = acl_check('encounters', 'auth_a', $user);
    if ($acl_allow) {
        $strQuery = 'UPDATE form_ros SET ';
        $strQuery .=' weight_change = "' . add_escape_custom($weight_change) . '",';
        $strQuery .=' weakness = "' .add_escape_custom( $weakness) . '",';
        $strQuery .=' fatigue = "' . add_escape_custom($fatigue) . '",';
        $strQuery .=' anorexia = "' . add_escape_custom($anorexia) . '",';
        $strQuery .=' fever = "' . add_escape_custom($fever) . '",';
        $strQuery .=' chills = "' . add_escape_custom($chills) . '",';
        $strQuery .=' night_sweats = "' . add_escape_custom($night_sweats) . '",';
        $strQuery .=' insomnia = "' . add_escape_custom($insomnia) . '",';
        $strQuery .=' irritability = "' . add_escape_custom($irritability) . '",';
        $strQuery .=' heat_or_cold = "' . add_escape_custom($heat_or_cold) . '",';
        $strQuery .=' intolerance = "' . add_escape_custom($intolerance) . '",';
        $strQuery .=' change_in_vision = "' . add_escape_custom($change_in_vision) . '",';
        $strQuery .=' glaucoma_history = "' . add_escape_custom($glaucoma_history) . '",';
        $strQuery .=' eye_pain = "' . add_escape_custom($eye_pain) . '",';
        $strQuery .=' irritation = "' . add_escape_custom($irritation) . '",';
        $strQuery .=' redness = "' . add_escape_custom($redness) . '",';
        $strQuery .=' excessive_tearing = "' . add_escape_custom($excessive_tearing) . '",';
        $strQuery .=' double_vision = "' . add_escape_custom($double_vision) . '",';
        $strQuery .=' blind_spots = "' . add_escape_custom($blind_spots) . '",';
        $strQuery .=' photophobia = "' . add_escape_custom($photophobia) . '",';
        $strQuery .=' hearing_loss = "' . add_escape_custom($hearing_loss) . '",';
        $strQuery .=' discharge = "' . add_escape_custom($discharge) . '",';
        $strQuery .=' pain = "' . add_escape_custom($pain) . '",';
        $strQuery .=' vertigo = "' . add_escape_custom($vertigo) . '",';
        $strQuery .=' tinnitus = "' . add_escape_custom($tinnitus) . '",';
        $strQuery .=' frequent_colds = "' . add_escape_custom($frequent_colds) . '",';
        $strQuery .=' sore_throat = "' . add_escape_custom($sore_throat) . '",';
        $strQuery .=' sinus_problems = "' . add_escape_custom($sinus_problems) . '",';
        $strQuery .=' post_nasal_drip = "' . add_escape_custom($post_nasal_drip) . '",';
        $strQuery .=' nosebleed = "' . add_escape_custom($nosebleed) . '",';
        $strQuery .=' snoring = "' . add_escape_custom($snoring) . '",';
        $strQuery .=' apnea = "' . add_escape_custom($apnea) . '",';
        $strQuery .=' breast_mass = "' . add_escape_custom($breast_mass) . '",';
        $strQuery .=' breast_discharge = "' . add_escape_custom($breast_discharge) . '",';
        $strQuery .=' biopsy = "' . add_escape_custom($biopsy) . '",';
        $strQuery .=' abnormal_mammogram = "' . add_escape_custom($abnormal_mammogram) . '",';
        $strQuery .=' cough = "' . add_escape_custom($cough) . '",';
        $strQuery .=' sputum = "' . add_escape_custom($sputum) . '",';
        $strQuery .=' shortness_of_breath = "' . add_escape_custom($shortness_of_breath) . '",';
        $strQuery .=' wheezing = "' . add_escape_custom($wheezing) . '",';
        $strQuery .=' hemoptsyis = "' . add_escape_custom($hemoptsyis) . '",';
        $strQuery .=' asthma = "' . add_escape_custom($asthma) . '",';
        $strQuery .=' copd = "' . add_escape_custom($copd) . '",';
        $strQuery .=' chest_pain = "' . add_escape_custom($chest_pain) . '",';
        $strQuery .=' palpitation = "' . add_escape_custom($palpitation) . '",';
        $strQuery .=' syncope = "' . add_escape_custom($syncope) . '",';
        $strQuery .=' pnd = "' . add_escape_custom($pnd) . '",';
        $strQuery .=' doe = "' . add_escape_custom($doe) . '",';
        $strQuery .=' orthopnea = "' . add_escape_custom($orthopnea) . '",';
        $strQuery .=' peripheal = "' . add_escape_custom($peripheal) . '",';
        $strQuery .=' edema = "' . add_escape_custom($edema) . '",';
        $strQuery .=' legpain_cramping = "' . add_escape_custom($legpain_cramping) . '",';
        $strQuery .=' history_murmur = "' . add_escape_custom($history_murmur) . '",';
        $strQuery .=' arrythmia = "' . add_escape_custom($arrythmia) . '",';
        $strQuery .=' heart_problem = "' . add_escape_custom($heart_problem) . '",';
        $strQuery .=' dysphagia = "' . add_escape_custom($dysphagia) . '",';
        $strQuery .=' heartburn = "' . add_escape_custom($heartburn) . '",';
        $strQuery .=' bloating = "' . add_escape_custom($bloating) . '",';
        $strQuery .=' belching = "' . add_escape_custom($belching) . '",';
        $strQuery .=' flatulence = "' . add_escape_custom($flatulence) . '",';
        $strQuery .=' nausea = "' . add_escape_custom($nausea) . '",';
        $strQuery .=' vomiting = "' . add_escape_custom($vomiting) . '",';
        $strQuery .=' hematemesis = "' . add_escape_custom($hematemesis) . '",';
        $strQuery .=' gastro_pain = "' . add_escape_custom($gastro_pain) . '",';
        $strQuery .=' food_intolerance = "' . add_escape_custom($food_intolerance) . '",';
        $strQuery .=' hepatitis = "' . add_escape_custom($hepatitis) . '",';
        $strQuery .=' jaundice = "' . add_escape_custom($jaundice) . '",';
        $strQuery .=' hematochezia = "' . add_escape_custom($hematochezia) . '",';
        $strQuery .=' changed_bowel = "' . add_escape_custom($changed_bowel) . '",';
        $strQuery .=' diarrhea = "' . add_escape_custom($diarrhea) . '",';
        $strQuery .=' constipation = "' . add_escape_custom($constipation) . '",';
        $strQuery .=' polyuria = "' . add_escape_custom($polyuria) . '",';
        $strQuery .=' polydypsia = "' . add_escape_custom($polydypsia) . '",';
        $strQuery .=' dysuria = "' . add_escape_custom($dysuria) . '",';
        $strQuery .=' hematuria = "' . add_escape_custom($hematuria) . '",';
        $strQuery .=' frequency = "' . add_escape_custom($frequency) . '",';
        $strQuery .=' urgency = "' . add_escape_custom($urgency) . '",';
        $strQuery .=' incontinence = "' . add_escape_custom($incontinence) . '",';
        $strQuery .=' renal_stones = "' . add_escape_custom($renal_stones) . '",';
        $strQuery .=' utis = "' . add_escape_custom($utis) . '",';
        $strQuery .=' hesitancy = "' . add_escape_custom($hesitancy) . '",';
        $strQuery .=' dribbling = "' . add_escape_custom($dribbling) . '",';
        $strQuery .=' stream = "' . add_escape_custom($stream) . '",';
        $strQuery .=' nocturia = "' . add_escape_custom($nocturia) . '",';
        $strQuery .=' erections = "' . add_escape_custom($erections) . '",';
        $strQuery .=' ejaculations = "' . add_escape_custom($ejaculations) . '",';
        $strQuery .=' g = "' . add_escape_custom($g) . '",';
        $strQuery .=' p = "' . add_escape_custom($p) . '",';
        $strQuery .=' ap = "' . add_escape_custom($ap) . '",';
        $strQuery .=' lc = "' . add_escape_custom($lc) . '",';
        $strQuery .=' mearche = "' . add_escape_custom($mearche) . '",';
        $strQuery .=' menopause = "' . add_escape_custom($menopause) . '",';
        $strQuery .=' lmp = "' . add_escape_custom($lmp) . '",';
        $strQuery .=' f_frequency = "' . add_escape_custom($f_frequency) . '",';
        $strQuery .=' f_flow = "' . add_escape_custom($f_flow) . '",';
        $strQuery .=' f_symptoms = "' . add_escape_custom($f_symptoms) . '",';
        $strQuery .=' abnormal_hair_growth = "' . add_escape_custom($abnormal_hair_growth) . '",';
        $strQuery .=' f_hirsutism = "' . add_escape_custom($f_hirsutism) . '",';
        $strQuery .=' joint_pain = "' . add_escape_custom($joint_pain) . '",';
        $strQuery .=' swelling = "' . add_escape_custom($swelling) . '",';
        $strQuery .=' m_redness = "' . add_escape_custom($m_redness) . '",';
        $strQuery .=' m_warm = "' . add_escape_custom($m_warm) . '",';
        $strQuery .=' m_stiffness = "' . add_escape_custom($m_stiffness) . '",';
        $strQuery .=' muscle = "' . add_escape_custom($muscle) . '",';
        $strQuery .=' m_aches = "' . add_escape_custom($m_aches) . '",';
        $strQuery .=' fms = "' . add_escape_custom($fms) . '",';
        $strQuery .=' arthritis = "' . add_escape_custom($arthritis) . '",';
        $strQuery .=' loc = "' . add_escape_custom($loc) . '",';
        $strQuery .=' seizures = "' . add_escape_custom($seizures) . '",';
        $strQuery .=' stroke = "' . add_escape_custom($stroke) . '",';
        $strQuery .=' tia = "' . add_escape_custom($tia) . '",';
        $strQuery .=' n_numbness = "' . add_escape_custom($n_numbness) . '",';
        $strQuery .=' n_weakness = "' . add_escape_custom($n_weakness) . '",';
        $strQuery .=' paralysis = "' . add_escape_custom($paralysis) . '",';
        $strQuery .=' intellectual_decline = "' . add_escape_custom($intellectual_decline) . '",';
        $strQuery .=' memory_problems = "' . add_escape_custom($memory_problems) . '",';
        $strQuery .=' dementia = "' . add_escape_custom($dementia) . '",';
        $strQuery .=' n_headache = "' . add_escape_custom($n_headache) . '",';
        $strQuery .=' s_cancer = "' . add_escape_custom($s_cancer) . '",';
        $strQuery .=' psoriasis = "' . add_escape_custom($psoriasis) . '",';
        $strQuery .=' s_acne = "' . add_escape_custom($s_acne) . '",';
        $strQuery .=' s_other = "' . add_escape_custom($s_other) . '",';
        $strQuery .=' s_disease = "' . add_escape_custom($s_disease) . '",';
        $strQuery .=' p_diagnosis = "' . add_escape_custom($p_diagnosis) . '",';
        $strQuery .=' p_medication = "' . add_escape_custom($p_medication) . '",';
        $strQuery .=' depression = "' . add_escape_custom($depression) . '",';
        $strQuery .=' anxiety = "' . add_escape_custom($anxiety) . '",';
        $strQuery .=' social_difficulties = "' . add_escape_custom($social_difficulties) . '",';
        $strQuery .=' thyroid_problems = "' . add_escape_custom($thyroid_problems) . '",';
        $strQuery .=' diabetes = "' . add_escape_custom($diabetes) . '",';
        $strQuery .=' abnormal_blood = "' . add_escape_custom($abnormal_blood) . '",';
        $strQuery .=' anemia = "' . add_escape_custom($anemia) . '",';
        $strQuery .=' fh_blood_problems = "' . add_escape_custom($fh_blood_problems) . '",';
        $strQuery .=' bleeding_problems = "' . add_escape_custom($bleeding_problems) . '",';
        $strQuery .=' allergies = "' . add_escape_custom($allergies) . '",';
        $strQuery .=' frequent_illness = "' . add_escape_custom($frequent_illness) . '",';
        $strQuery .=' hiv = "' . add_escape_custom($hiv) . '",';
        $strQuery .=' hai_status = "' . add_escape_custom($hai_status) . '"';
        $strQuery .= ' WHERE id = ?';

        $result = sqlStatement($strQuery, array($rosId));

        if ($result !== FALSE) {

            $xml_string .= "<status>0</status>";
            $xml_string .= "<reason>The Review of Systems has been updated</reason>";
        } else {
            $xml_string .= "<status>-1</status>";
            $xml_string .= "<reason>ERROR: Sorry, there was an error processing your data. Please re-submit the information again.</reason>";
        }
    } else {
        $xml_string .= "<status>-2</status>\n";
        $xml_string .= "<reason>You are not Authorized to perform this action</reason>\n";
    }
} else {
    $xml_string .= "<status>-2</status>";
    $xml_string .= "<reason>Invalid Token</reason>";
}

$xml_string .= "</reviewofsystems>";
echo $xml_string;
?>